services:
  build:
    container_name: build
    build:
      context: .
      dockerfile: ./build/Dockerfile
    working_dir: /gwent
    volumes:
      - ./build:/gwent
      - .env:/gwent/.env
    environment:
      TZ: Europe/Zurich
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    working_dir: /gwent
    volumes:
      - ./server:/gwent
      - ./build/public:/gwent/public
      - ./build/assets:/gwent/assets
      - .env:/gwent/.env
    environment:
      TZ: Europe/Zurich
    ports:
      - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    restart: always