services:
  not-gwent:
    build:
      context: .
    working_dir: /not-gwent-online
    volumes:
      - .:/not-gwent-online
    ports:
      - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"