services:
  not-gwent-online:
    container_name: not-gwent-online
    build:
      context: .
    working_dir: /not-gwent-online
    volumes:
      - .:/not-gwent-online
    environment:
      TZ: Europe/Zurich
    ports:
      - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    restart: always